id: P009076
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28925
  title: མཐོ་སྒང་གི་རྣམ་ཤེས
  author: ''
  volumes:
    1eb7e54b02a44ec2abfff7564323f9cf:
      image_group_id: I4871
      title: ''
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
