id: I86747D72
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:05:07+00:00'
last_modified: '2022-06-08T08:26:50.329472+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28925
  title: མཐོ་སྒང་གི་རྣམ་ཤེས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    C2AE:
      image_group_id: I4871
      title: ''
      total_pages: 214
      order: 1
      base_file: C2AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
